# EJERCICIO 05: FACTORIAL DE UN NUMERO POSITIVO
# HACER UN PROGRAMA PARA CALCULAR EL FACTORIAL DE UN NUMERO POSITIVO

numero = int(input('Digite un numero: ')) # AQUI VAMOS A NECESITAR UN CICLO WHILE, VAMOS A DECIRLE QUE SI LA CONDICION DE QUE EL NUMERO SEA MENOR A 0, ESTO NOS LLEVA A UN NEGATIVO
while numero < 0: # Mientras el numero sea MENOR A 0 SERA negativo
    print('Error -> El numero tiene que ser POSITIVO')
    numero = int(input('Digite un numero: ')) # VAMOS A PEDIR DE NUEVO QUE DIGITE EL NUMERO, SE VA DIGITAR EL VALOR HASTA QUE SEA  POSITIVO,RECUERDEN QUE HAY QUE CONVERTIR A ENTERO CON LA FUNCION IMPUT
# VAMOS A CREAR UNA VARIABLE QUE SE LLAMA FACTORIAL,YA LOGRAMOS QUE EL USUARIO NOS DE EL NUMERO POSITIVO,COMENZAMOS LA VARIABLE FACTORIAL EN 1
factorial = 1 # LA VARIABLE PARA CALCULAR EL FACTORIAL
for i in range(1,numero+1): # CON EL CICLO FOR USANDO EL ITERADOR EN UN RANGO,VAMOS A USAR LA FUNCION DE RANGE, LE DECIMOS QUE COMIENCE EN 1 Y LA VARIABLE NUMERO + 1, QUE ABARQUE EL NUMERO EN SU TOTALIDAD
    factorial *= i  # usamos el factorial,con el operador de asignacion simplificado,quitando la identacacion usamos un print sacando la identacion
print(f'\nEl Factorial del numero{numero} POSITIVO ingresado es: {factorial}') # VAMOS A MOSTRARLES CON LAS LLAVES EL FACTORIAL, y entre llaves tambien la variable numero


