//BASICAMENTE UNA CLASE ES UNA PLANTILLA, HEMOS DEFINIDO UNA CLASE Y LA HEMOS LLAMADO PERSONA
    //ESTA CLASE VA A TENER ATRIBUTOS Y METODOS LOS CUALES VAN A EXTRAER LA INFORMACION DE LO QUE 
    //ES EL MUNDO REAL,EJ:UNA CLASE PUEDE TENER COMO ATRIBUTO EL NOMBRE,APELLIDO DE LA PERSONA,UN TELEFONO,VARIOS DATOS ETC
    //TAMBIEN PUEDE TENER METODOS PARA TOMAR LA EDAD,MODIFICAR LA EDAD DE LA PERSONA 
    //UNA CLASE ES UNA PLANTILLA DE LAS CUALES VAMOS A PODER CREAR OBJETOS
    // ES A PARTIR DE LA CLASE QUE PODEMOS CREAR OBJETOS
    // EN LO OBJETOS VAMOS A ASIGNAR VALORES,UN OBJETO ES UNA INSTANCIA DE UNA CLASE
    //EN LAS CLASES VAMOS A DEFINIR LO QUE SON ATRIBUTOS Y METODOS DE MANERA GENERAL,LA CLASE SERA EL MOLDE
package Clases;

public class Persona {
    
    
}
