//BASICAMENTE UNA CLASE ES UNA PLANTILLA, HEMOS DEFINIDO UNA CLASE Y LA HEMOS LLAMADO PERSONA
    //ESTA CLASE VA A TENER ATRIBUTOS Y METODOS LOS CUALES VAN A EXTRAER LA INFORMACION DE LO QUE 
    //ES EL MUNDO REAL,EJ:UNA CLASE PUEDE TENER COMO ATRIBUTO EL NOMBRE,APELLIDO DE LA PERSONA,UN TELEFONO,VARIOS DATOS ETC
    //TAMBIEN PUEDE TENER METODOS PARA TOMAR LA EDAD,MODIFICAR LA EDAD DE LA PERSONA 
    //UNA CLASE ES UNA PLANTILLA DE LAS CUALES VAMOS A PODER CREAR OBJETOS
    // ES A PARTIR DE LA CLASE QUE PODEMOS CREAR OBJETOS
    // EN LO OBJETOS VAMOS A ASIGNAR VALORES,UN OBJETO ES UNA INSTANCIA DE UNA CLASE
    //EN LAS CLASES VAMOS A DEFINIR LO QUE SON ATRIBUTOS Y METODOS DE MANERA GENERAL,LA CLASE SERA EL MOLDE
package Clases;

public class Persona { //UNA CLASE ES NUESTRA PLANTILLA,POSEE ARIBUTOS Y MÉTODOS
    //ATRIBUTO DE LA CLASE (CARACTERISTICA)
    //UN ATRIBUTO ES UNA CARACTERISTICA QUE VAMOS A ASOCIAR A NUESTRA CLASE
    //DEFINIMOS LOS ATRIBUTOS SON DE TIPO STRING,UN METODO ES UNA PARTE DE CODIGO QUE VAMOS A REUTILIZAR
    //POR ESTO ES QUER LO PODEMOS LLAMAR LAS VECES QUE SEAN NECESARIO,UN MÉTODO PUEDE RECIBIR VARIOS VALORES
    //ESTOS SE CONOCEN COMO ARGUMENTOS,UN METODO TAMBIEN PUEDE REGRESAR UN VALOR,SE LO LLAMA VALOR DE RETORNO,QUE TAMBIEN PUEDE REGRESAR A NUESTRO METODO
    //PARA DEFINIR UN METODO COMENZAMOS PONIENDO PUBLIC,PUBLIC ES PARA INDICAR QUE EL METODO SE PUEDE UTILIZAR FUERA DE ESTA CLASE,TAMBIEN ESTA LA FORMA PRIVADA
    //LUEGO VAMOS A PONER VOID, EL VOID INDICA QUE NO REGRESA NINGUN TIPO DE INFORMACION, EN EL NOMBRE DEL METODO
    String nombre; //definimos los atributos son de tipo string
    String apellido;//desde la linea 12 a la 14 todo esto es una Plantilla
    //METODO DE LA CLASE(ACCIONES)
    //PARA DEFINIR UN METODO COMENZAMOS PONIENDO PUBLIC,PUBLIC ES PARA INDICAR QUE EL METODO SE PUEDE UTILIZAR FUERA DE ESTA CLASE,TAMBIEN ESTA LA FORMA PRIVADA
    //LUEGO VAMOS A PONER VOID, EL VOID INDICA QUE NO REGRESA NINGUN TIPO DE INFORMACION, EN EL NOMBRE DEL METODO que le pondremos ahora VAMOS A UTILIZAR LA 
    //NOMENCLATURA CAMEL CASE,LOS PARENTESIS INDICAN QUE PODEMOS RECIBIR INFORMACION QUE PUEDE RECIBIR UN MÉTODO SE CONOCE COMO ARGUMENRTO,QUE PUEDE RECIBIR O NO UN METODO
    public void obterInformacion(){      //EN ESTE CASO EN ESTE ARGUMENTO NO VAMOS RACIBIR NADA
        System.out.println("Nombre: "+nombre); //AQUI DENTRO DE LO QUE ES METODOS VAMOS A ESCRIBIR Nombre, y Nombre despues de la concatenacion Nombre es:UN ATRIBUTO DE LA CLASE
        System.out.println("Apellido: "+apellido);//Y NO IMPORTA QUE NO SE DEFINA DENTRO DEL METODO,PORQUE AL SER UN ATRIBUTO SE INICIAR DENTRO DE CUALQUIER METODO DEFINIDO DENTRO DE LA CLASE
        
                                                
        
        
    }
    
    
    
    
}
