/*
AQUI YA TENEMOS CREADA OTRA CLASE,DONDE QUEREMOS PONER NUESTRO METODO MAIN,PRIMERO CREAMOS EL METODO MAIN,DESDE ESTE METODO
HASTA AHORA HEMOS CREADO UNA VARIABLE LLAMADA PERSONA1,ESTA VARIABLE TIENE UN EFECTO EN LA MEMORIA, LO QUE ESTAMOS HACIENDO ES SOLO RESERVAR ESPACIO EN LA MEMORIA PARA ESTA
VARIABLE QUE ESTA DEFINIDA DENTRO DEL METODO MAIN,DE ESTA MANERA ES UNA VARIABLE DE TIPO LOCAL AL MAIN,CUANDO NOSOTROS CREAMOS UNA VARIABLE DENTRO DEL MAIN,ES UNA VARIABLE LOCAL
SE DECLARA EN ESTE METODO QUE AL TERMINAR, DESTRUYE LA VARIABLE,CADA VEZ QUE NOSOTROS CREAMOS UNA VARIABLE,DENTRO DEL METODO MAIN, EJECUTAMOS Y AL TERMINAR LA EJECUCION EN CONSOLA
SE DESTRUYE TODO LOS QUE SE HABIA GUAREDADO EN LA MENORIA DE ESA VARIABLE,LA VARIABLE DESAPARECE,DESTRUIDA ,PERO CUANDO LA DEFINIMOS Y ADEMAS LE ASIGNAMOS UNA REFERENCIA DE UN OBJETO
UTILIZANDO LA CLASE EN ESTE CASO,LA CLASE ES UN TIPO DE CLASE PERSONA,CUANDO ASIGNAMOS AQUI,QUE PODEMOS ASIGNAR UN TIPO STRING,ENTERO,BOOLEANO,FLOAT,AQUI ESTAMOS ASIGNANDO UN TIPO 
CLASE A UNA VARIABLE PERSONA HASTA AQUI ES SOLO UNA VARIABLE DEL METODO MAIN,PERO AQUI YA LA ESTAMOS INSTANCIANDO Y LA ESTAMOS TRANSFORMANDO ESA VARIABLE AUN OBJETO,INSTANCIAR ES CREAR
UTILIZANDO LA CLASE Y ESTE NEW,NEW ES COMO UN PUNTERO,ES EL QUE NOS DA ACCESO A ESE ESPACIO DE MENORIA, EL NEW ES UNA PALABRA RESERVADA Y TAMBIEN SE NECESITA EL CONSTRUCTOR,NECE-
SITAMOS EL NEW, Y LUEGO EL CONTRUCTOR PERSONA CON LOS PARENTESIS, ESTE CONTRUCTOR NECESITA LA PALABRA NEW Y NO SE PUEDE PONER EN OTRO LUGAR, EL UNICO FORMATO ES ESTE NEW Y DESPUES
EL CONSTRUCTOR,POR ESTO ES UN METODO ESPECIAL, NO SE PUEDE MANDAR A LLAMAR POSTERIORMENTE,SI NO SOLAMENTE AL MOMENTO DE CREAR OBJETOS,EL NEW Y EL CONSTRUCTOR ES CADA VEZ QUE 
VAMOS A INSTANCIAR A RECURRIR AL TIPO PERSONA, EL EFECTO EN LA MEMORIA ES QUE SE GUARDA O RESERVA MEMORIA PARA EL OBJETO LA VARIABLE SE TRANSFORMO EN UN OBJETO,ESTE VA A TENER 
UNA REFERENCIA DE MEMORIA HEXADECIMAL, LOS VALORES EN JAVA SE INICIAN MAYORMENTE CON 0 Y X,ESTE VALOR ES UNA REFERENCIA DE MEMORIA,ESTA REFERENCIA SE LE ASIGNA A LA VARIABLE
PERSONA1, DE ESTA MANERA ES QUE LA VARIABLE PUEDE ACCEDER A LOS ATRIBUTOS DEL OBJETO CREADO,PUEDE ACCEDER A LOS METODOS PARA ACTUAR SOBRE LOS VALORES EN ESTE CASO,NOMBRE Y APELLIDO

*/
package Clases; //LA CLASE PERSONA ES NUESTRA PLANTILLA, EN LA CUAL DEFINIMOS,CARACTERISTICAS O ATRIBUTOS Y TAMBIEN LOS METODOS O ACCIONES


public class PruebaPersona { //utilicamos el Pascal case(comienzan las dos con mayusculas) 
    public static void main(String[] args) { //El metodo main esta justamente para ejecutar el programa
        Persona persona1;  //vamos a comenzar con la creacion de un objeto, vamos hacerlo llamando a la clase persona 
        persona1 = new Persona();//LLAMAMOS AL CONTRUCTOR,ESTE CONTRUCTOR NOS PERMITE ASIGMAR VALORES AL OBJETO DE QUE LO CREAMOS,UNA VARIABLE SE ALMACENAEN UNA PARTE DIFERENTE,QUE 
        persona1.nombre = "Ariel";    //LOS OBJETOS EN LO QUE ES LA MEMORIA,POR ESO JAVA LOS ADMINISTRA DE MANERA DIFERENTE,EL CONTRUCTOR ES UN METODO ESPECIAL DONDE RESERBA MEMORIA PARA
        persona1.apellido = "Betancud"; //PODER CREAR OBJETOS,LO QUE HACE ES QUE LA CREAR EL OBJETO,EL CONTRUCTOR LE REGRESA LAS REFERENCIAS DONDE SE CREO EL OBJETO Y SE LO ASIGNA A LA VARIABLE
        persona1.obterInformacion(); //UNA VEZ ECHA ESTA CONECCION SE PUEDE ACCEDER A LOS ATRIBUTOS Y METODOS DE LA CLASE PERSONA EN ESTE CASO
        
        //CREAMOS UN NUEVO OBJETO
        Persona persona2 = new Persona();//null significa que tiene ausencia de valor, no tiene ningun valor cargado el objeto
        System.out.println("persona2 = " + persona2);
        System.out.println("persona1 = " + persona1);
        persona2.obterInformacion();//cada objeto tiene su propio informacion,los objetos no comparten informacion,lo único que estan compartiendo son las caracteristicas de nombre y apellido
        persona2.nombre = "Osvaldo";                           //es lo que estan pidiendo cada objeto, es lo unico que estan compartiendo, que son los atributos que hemos definido ya en la clase
        persona2.apellido = "Giordanini";                                  
        persona2.obterInformacion();
    }
}
           /*POR OTRO LADO LOS OBJETOS, EN ESTE CASO PERSONA1 Y PERSONA2,(SON LAS INSTANCIAS =NEW Persona())esta creando un objeto son las instancias que creamos de la clase para 
           utilizar las caracteristicas y acciones accediendo a la informacion o valor,cada objeto es distinto y se lo conoce o llama instancia que es lo mismo que decir objeto
 
*/